### ISSUE TITLE
Specify path to gpustat for each host

### ISSUE THREAD

**Issue by Rizhiy** [wookayin/gpustat-web#10]
I generally don't like to install anything into my system python, therefore it would be nice if it was possible to provide path to gpustat for each host.

**Comment by wookayin** [comment]
You can do like:

```
gpustat-web ... --exec /home/username/miniconda3/bin/gpustat --color --gpuname-width
```

I can also add `--login` or (`-i`) option, or more generally `--ssh-options` to allow use of login shell so that `~/.profile` can be sourced.

**Comment by wookayin** [comment]
Actually with the current version, the $PATH variable is populated as in ~/.zshenv, ~/.profile. Can you try `ssh <node> bash 'echo $PATH'` and see what happens?

**Comment by Rizhiy** [comment]
Just default paths: 
`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`

I have a pretty complicated python setup, so I think I will just use `--exec`, thanks.
