### ISSUE TITLE
CPU stats errors

### ISSUE THREAD

**Issue by yanaiela** [wookayin/gpustat-web#11]
hey,

I can't make it work for showing cpu usage.
I follow the command from the README.md file, and I'm getting these errors:
```command not found: ascii-bar```
```command not found: cpu```

any idea how to solve this issue?

**Comment by wookayin** [comment]
Sorry that was my personal note, not publicly available scripts. You can grab ones I'm using if you're interested:

https://github.com/wookayin/dotfiles/blob/master/bin/ascii-bar
https://github.com/wookayin/dotfiles/blob/master/bin/cpu-usage

**Comment by yanaiela** [comment]
ah, great. thanks!
