### ISSUE TITLE
specify different path to gpustat

### ISSUE THREAD

**Issue by jh-yi** [wookayin/gpustat-web#16]
Hi, I wonder is it possible to specify different paths to gpustat while using --exec?  
e.g. 
python -m gpustat_web --exec 'path_in_machineA --color --gpuname-width 25' machine A --exec 'path_in_machineB --color --gpuname-width 25' machine B 

Thanks a lot in advance!

**Comment by wookayin** [comment]
You can use absolute paths, e.g.:

```
python -m gpustat_web --exec '/path/to/some/custom/python_installation/bin/gpustat' ...
```
