### ISSUE TITLE
Feature request - create an endpoint to expose gpustat_web to the command line

### ISSUE THREAD

**Issue by imaluengo** [wookayin/gpustat-web#21]
Would be great to be able to access this information through the command line too.

It would require very little modification:

1. Define a new endpoint 

```
async def cmd_handler(request):
    body = ''
    for _, status in context.host_status.items():
        if not status:
            continue
        body += status
    return web.Response(text=body)
```

2. Register the endpoint:

```
app.router.add_get('/cmd', cmd_handler)
```

And now the same user interface in the browser can be accessible from the command line by just using curl

`$> curl http://localhost:48109/cmd`

Which could be conveniently put into an alias `alias gpustat-web=$(curl HTTP://localhost:48109/cmd)`

**Comment by wookayin** [comment]
Done via 9abfd1e. I've added a new feature: you can do like
```
curl http://localhost:48109/gpustat.ansi
```
