### ISSUE TITLE
Allow skipping SSH host key verification (known_hosts=None in asyncssh.connect)

### ISSUE THREAD

**Issue by chunxiao369** [wookayin/gpustat-web#23]
issus: 
Disconnected : x.x.x.x, Host key is not trusted

**Comment by wookayin** [comment]
What does that do? Does that bypass the host key verification? Do you want to write a PR -- maybe as an option?

**Comment by wookayin** [comment]
gpustat v0.3.0 now has a new `--no-verify-host` option.
