### ISSUE TITLE
Connect to nodes through custom port different from the default port

### ISSUE THREAD

**Issue by ssslkj123** [wookayin/gpustat-web#8]
Question：
    Today I try to use this tool for collect the GPU status for another nodes, but the nodes ssh port has been changed port to 51255 ， so I use command as follow ：

`# python3 -m gpustat_web --port 48109   node12:51255`
`Hosts : ['node12:51255']`
`Cmd   : gpustat --color --gpuname-width 25`
`Disconnected : node12:51255, [Errno -2] Name or service not known`
`[node12:51255] Disconnected, retrying in 5.0 sec...`
`======== Running on http://0.0.0.0:48109 ========`
`(Press CTRL+C to quit)`
`Disconnected : node12:51255, [Errno -2] Name or service not known`
`[node12:51255] Disconnected, retrying in 5.0 sec...`
`^C... Terminating the application`

If I wanna to change ssh port for the nodes ，what should I do , Tks.

**Comment by wookayin** [comment]
I'll need to implement this feature, allowing a syntax like `<HOST>[:<PORT>]`. I wish asyncssh would respect the `~/.ssh/config` config so that users can specify default port/authentication scheme to connect with, but unfortunately it does not.

**Comment by ConanCui** [comment]
Hi, how could we solve this problem now?

**Comment by wookayin** [comment]
@ConanCui Implemented in 1c332581. Please try out and feel free to reopen if you find any issues.
