### ISSUE TITLE
Add better errors

### ISSUE THREAD

**Issue by Rizhiy** [wookayin/gpustat-web#9]
Can you add an option to print more error information.

I run `python -m gpustat_web --port 10000` and it responds with "[localhost] error, exitcode=127", which is not very helpful.
I tried using `--verbose`, but that didn't improve the situation.

**Comment by wookayin** [comment]
Hi @Rizhiy, thanks for your suggestion. I've made a modification so that stderr can be printed if the remote command fails. Could you please try again and see that looks good to you?

**Comment by Rizhiy** [comment]
Yes, that works, thanks.
